//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach.Lang {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kursach.Lang.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1Funtion {
            get {
                object obj = ResourceManager.GetObject("_1Funtion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2Funtion {
            get {
                object obj = ResourceManager.GetObject("_2Funtion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !!!При значенні .
        /// </summary>
        internal static string ErrorDiscribe {
            get {
                return ResourceManager.GetString("ErrorDiscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неможна виконувати дію з таким кроком.
        /// </summary>
        internal static string ErrorDx {
            get {
                return ResourceManager.GetString("ErrorDx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dx неможе дорівнювати 0.
        /// </summary>
        internal static string ErrorDxIs0 {
            get {
                return ResourceManager.GetString("ErrorDxIs0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  уже открита.
        /// </summary>
        internal static string ErrorIsOpenForm {
            get {
                return ResourceManager.GetString("ErrorIsOpenForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Xmax повинне бути більше Xmin.
        /// </summary>
        internal static string ErrorMaxLowMin {
            get {
                return ResourceManager.GetString("ErrorMaxLowMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sin(q) = 0, Log(a+x) = 0.
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всі поля повинні бути заповнені.
        /// </summary>
        internal static string ErrorTextIsNull {
            get {
                return ResourceManager.GetString("ErrorTextIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Толстоноженко Станіслав Олегович
        ///ІТ-71/2.
        /// </summary>
        internal static string NameStudnet {
            get {
                return ResourceManager.GetString("NameStudnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Student {
            get {
                object obj = ResourceManager.GetObject("Student", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тут знаходяться результати обчислень та графік а також при яких параметров помилка.
        /// </summary>
        internal static string TextAboutFormGraf {
            get {
                return ResourceManager.GetString("TextAboutFormGraf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почати.
        /// </summary>
        internal static string TextButtomStart {
            get {
                return ResourceManager.GetString("TextButtomStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помилки : .
        /// </summary>
        internal static string TextError {
            get {
                return ResourceManager.GetString("TextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string TextErrorForMesanger {
            get {
                return ResourceManager.GetString("TextErrorForMesanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Щоб продовжити закрийте вкладки.
        ///Закрити вкладки ?.
        /// </summary>
        internal static string TextErrorOpenForm {
            get {
                return ResourceManager.GetString("TextErrorOpenForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Щоб продовжити потрібно ввести дані в поля.
        ///
        ///В поле можна ввести (0-9 , -).
        ///
        ///Якщо забули ввести (-) видаліть всі дані
        ///з поля і введіть повторно.
        ///
        ///Також в полі передбачено запобігання 
        ///повторне  натискання &apos;,&apos; і &apos;-&apos;.
        ///
        ///А також &apos;-&apos; можна ввести тільки 
        ///на початку введення..
        /// </summary>
        internal static string TextInformation {
            get {
                return ResourceManager.GetString("TextInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Представлено при яких аргументах &apos;x&apos; маємо значення &apos;y&apos;.
        ///А також помилки при яких значень і графік цих координат..
        /// </summary>
        internal static string TextInformationGraf {
            get {
                return ResourceManager.GetString("TextInformationGraf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть дані.
        /// </summary>
        internal static string TextInputeData {
            get {
                return ResourceManager.GetString("TextInputeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кількість ітерацій: .
        /// </summary>
        internal static string TextIteration {
            get {
                return ResourceManager.GetString("TextIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функція 1 .
        /// </summary>
        internal static string TextMenuF1 {
            get {
                return ResourceManager.GetString("TextMenuF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функція 2 .
        /// </summary>
        internal static string TextMenuF2 {
            get {
                return ResourceManager.GetString("TextMenuF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формула.
        /// </summary>
        internal static string TextMenuFormula {
            get {
                return ResourceManager.GetString("TextMenuFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Графіка.
        /// </summary>
        internal static string TextMenuGraf {
            get {
                return ResourceManager.GetString("TextMenuGraf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мова.
        /// </summary>
        internal static string TextMenuLang {
            get {
                return ResourceManager.GetString("TextMenuLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Англійська.
        /// </summary>
        internal static string TextMenuLangEng {
            get {
                return ResourceManager.GetString("TextMenuLangEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Українська.
        /// </summary>
        internal static string TextMenuLangUkr {
            get {
                return ResourceManager.GetString("TextMenuLangUkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Початковий екран.
        /// </summary>
        internal static string TextNameMainForm {
            get {
                return ResourceManager.GetString("TextNameMainForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Студент.
        /// </summary>
        internal static string TextStudent {
            get {
                return ResourceManager.GetString("TextStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Натисніть 
        ///Щоб подивитися інформацію про студента..
        /// </summary>
        internal static string TextStudentLabel {
            get {
                return ResourceManager.GetString("TextStudentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Час :.
        /// </summary>
        internal static string TextTimeWork {
            get {
                return ResourceManager.GetString("TextTimeWork", resourceCulture);
            }
        }
    }
}
